### PR TITLE
Added plotting option for mclust results

### PR DESCRIPTION
**Pull request by cjvanlissa**

### CODE REVIEW

**Comment by jrosen48** [comment]
This looks brilliant. Testing this locally. Would you be interested in being a contributor (i.e., on the DESCRIPTION file)? On behalf of my collaborators, we would like for you to be. In any case, thanks for this contribution.

**Comment by cjvanlissa** [comment]
Dear Joshua, I'd love to be noted as a contributor! Let me know if this code needs more work, or if I can help out with any other bits.

Best,
Caspar

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by jrosen48** [comment]
I think if we run devtools::document() this will pass! Will change DESCRIPTION too. Thanks so much @cjvanlissa!

**Comment by jrosen48** [comment]
Is your email address ending in `uu.nl` good to use or do you prefer a different address?

**Comment by jrosen48** [comment]
Sorry for all the posts, I'm not so good at GitHub yet :)

I made a few changes in the last few commits to the docs. One thing that I think we'll want to do is write the section of [`plot_profiles.R`](https://github.com/jrosen48/tidyLPA/blob/master/R/plot_profiles.R) to do the `ymin` and `ymax` calculations in a separate step so we can use `aes_string()` instead of `aes()`. I simply added `c("Value", "se", "Class", "Variable")` as global variables in [`helpers.R`](https://github.com/jrosen48/tidyLPA/blob/master/R/helpers.R), but this should be easy / not important to address, as it passes fine as it is now.

      # Add errorbars
      if (!is.null(ci)) {
          ci <- qnorm(.5 * (1 - ci))
          classplot <-
              classplot + geom_errorbar(
                  data = plotdat,
                  aes(
                      x = Class,
                      colour = Variable,
                      ymin = Value - (ci * se),
                      ymax = Value + (ci * se)
                  ),
                  position = position_dodge(width = .75)
              )
      }
      classplot + theme_bw()

**Pull request merged**
