### PR TITLE
Namespacing and package documentation

### PR DESCRIPTION
**Pull request by DJAnderson07**
I created some basic package documentation (e.g., `?tidyLPA`) and put all the imports there, removing them from each of the individual files.  This mostly helps with readability of code because you never have to do any namespacing of functions (e.g., `ggplot2::ggplot` becomes `ggplot` throughout). But, I also removed all the full package imports, and only imported the functions from the packages that were needed for the code and to create the vignettes. This helps reduce the likelihood of function conflicts (e.g., `mclust::map` and `purrr::map`) without generally having to worry about namespacing.

### CODE REVIEW

**Comment by jrosen48** [comment]
This is great, thank you SO much for your work on this!

**Comment by DJAnderson07** [comment]
I good! I'm glad you like it. One thing that I discovered after is that the new `usethis` package has a function `use_package_doc` that creates something similar. The default name of the file is then pkgname-package. I'm not sure if that's going to become a more consistent standard but it may be worth renaming this file to *tidyLPA-package.R* rather than just *tidyLPA*. It also has

```
#' @keywords internal
"_PACKAGE"
```
Which may be worth adding (I'm not sure, honestly, just thinking about aligning with convention).

**Comment by jrosen48** [comment]
Yep, sounds good. Let's add this!

**Comment by jrosen48** [comment]
Just confirming I ran my local tests on this (these tests don't run on Travis or CRAN because they require MPlus - but they should run if *you* run them) and they all pass (still).

**Pull request merged**
