### PR TITLE
Draft of version 1.0.0

### PR DESCRIPTION
**Pull request by cjvanlissa**
To do by Josh:
* Check vignettes and paper.md (?): Some examples and even sections are deprecated!
* Do you want to change the CITATION doc (in the inst/ directory) to something that includes CJ? Elsewhere you ask people to cite the software, which includes me as an author. I would appreciate it.
* Import pipe from dplyr or not? I added functionality to import / export the pipe.

Done by CJ:
* integrated all the code from our two versions
* addressed any conflicts
* debugged my functions
* tested all examples and removed \dontrun
* cleaned up useless/duplicate files from the repository
* Ensured vignettes show up in package
* Moved CJ up the authors list to second author. If you disagree, let's discuss
* Updated version number to 1.0.0
* Updated license: There were two license files, and my name was not included even though I own the copyright on some functions
* Replaced lubridate with tidyLPA in CITATION
* Hide as.tidyLPA function; it's not ready / useful yet
* Remove mplusAvailable(); it can be imported from MplusAutomation

### CODE REVIEW

**Comment by jrosen48** [comment]
C.J., you've done a brilliant job with this. I'm still working through things, especially some finer-grained things, including tests and documentation, that will take some time. A few quick questions:
- For the `package` argument to the `estimate_profiles()` function, what do you think of using `"mplus"` as the value to call mplus (instead of `MplusAutomation`)? I recognize this causes an issue with respect to the *name of the argument*; if you think this change is worth making, would it also be worth changing `package` to something like `software`? Thoughts?
- Can you plot the output of an MPlus function? Using an example, i seemed to get an error:

``` r
pisaUSA15[1:100, ] %>%
    select(broad_interest, enjoyment, self_efficacy) %>%
    single_imputation() %>%
    scale() %>%
    estimate_profiles(3, package = "MplusAutomation") %>% 
    plot_profiles()
#> Error in pisaUSA15[1:100, ] %>% select(broad_interest, enjoyment, self_efficacy) %>% : could not find function "%>%"
```

<sup>Created on 2019-01-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
- Thoughts on adding open and close parenthesis after every function call? I.e., `single_imputation()` instead of `single_imputation`. I *think* but am not sure that adding the open and close parenthesis is in style guides (it's at least implied in [the Tidyverse style guide](https://style.tidyverse.org/functions.html)
All for now; more (I hope) tomorrow.

**Comment by cjvanlissa** [comment]
Dear Josh, (please see the update to my pull request, with fixes to the issues below),

  *   For the package argument to the estimate_profiles() function, what do you think of using "mplus" as the value to call mplus (instead of MplusAutomation)? I recognize this causes an issue with respect to the name of the argument; if you think this change is worth making, would it also be worth changing package to something like software? Thoughts?

I had considered this, but decided that it made sense to have users be aware that, under the hood, these two specific packages are being used. It also provides easy compatibility if we were to ever add a method for another package (e.g., OpenMX). It also helps users find the original packages, thereby crediting the original authors, and having users find the original documentation easily.

But there is also something to be said for brevity. You make the call. I can also make both “mplus” and “MplusAutomation” synonymous arguments.

  *   Can you plot the output of an MPlus function? Using an example, i seemed to get an error:

Thank you for sending me this example! Your error is different from the one I’m getting. Mine says


Error in .cleanHashData(df = object$rdata, keepCols = object$usevariables,  :

  inherits(df, "data.frame") is not TRUE
This is because scale() returns a matrix, and estimate_profiles_mplus2 only accepts data.frames. I’ve now added a line to convert matrix to data.frame.

Your error, on the other hand, implies that the pipe operator is not loaded. That’s weird, I put it into our package. Are you 100% sure that you’ve installed the latest github version? With no other packages loaded except for tidyLPA, the pipe works fine for me.

pisaUSA15[1:100, ] %>%

    select(broad_interest, enjoyment, self_efficacy) %>%

    single_imputation() %>%

    scale() %>%

    estimate_profiles(3, package = "MplusAutomation") %>%

    plot_profiles()

#> Error in pisaUSA15[1:100, ] %>% select(broad_interest, enjoyment, self_efficacy) %>% : could not find function "%>%"

Created on 2019-01-27 by the reprex package<https://reprex.tidyverse.org> (v0.2.1)

  *   Thoughts on adding open and close parenthesis after every function call? I.e., single_imputation() instead of single_imputation. I think but am not sure that adding the open and close parenthesis is in style guides (it's at least implied in the Tidyverse style guide<https://style.tidyverse.org/functions.html>
All for now; more (I hope) tomorrow.

I’m fine with it. Could you please make these changes as you go over the documentation?
Tbh, I have never used (and slightly resent) the “tidy” syntax, so I was just playing around with it, and seeing what syntax it would accept. The reasons why are a discussion we should once have over a beer :p



Dr. Caspar J. van Lissa
Assistant professor of developmental data science
Utrecht University, dept. Methodology & Statistics
Sjoerd Groenmangebouw C1.19, 3584CH Utrecht, the Netherlands. Secretariat: +31 30 253 4438

**Comment by jrosen48** [comment]
Thanks so much Caspar. What do you think if we merge this and then I address changes through a PR? Having some difficulty pushing to your master. Tips are welcome, too.

**Comment by cjvanlissa** [comment]
You should accept my pull request. Then, make a new branch of your master. Make any changes in that branch, then sending a pull request to your main branch, and invite me to look at it :)

**Comment by jrosen48** [comment]
Sounds good!

**Pull request merged**
